#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>|
#                                                                                   |
#           /                    /              /\                                  |
#          /                    /              /  \                                 |
#         /                    /              /    \                                |
#        /                    /              /      \                               |
#                                    /      /        \                              |
#   \                              _/      /__________\                             |
#    \                          _ /       /------------\                            |
#     \                        /         /              \                           |
#      \______________________/         /                \                          |
#                                                                                   |
#                                     Chamo/SQD Studios Product                     |
#                                                                                   |
#/////////////// ChamoOrders V1.0.0ALPHA configuration file \\\\\\\\\\\\\\\\\\\\\\\\|
#                                                                                   |
#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<|

debug: false # We recommend not setting this to true, as it shows internal info and spams the console

language: en

database:
  type: SQLite # Usable options: MySQL, SQLite

  credentials: # Not Needed fot SQLite
    host: localhost
    port: 3306
    database: chamoorders
    username: root
    password: pass

# Order related settings
orders:
  new-order-settings:
    tax-percent: 0.1 # Extra percentage charged when a player creates a new order.
    default-max-orders: 3 # Set -1 to allow infinite. You can set permissions like chamoorders.maxorders.(number of orders) for a different one

  # Item settings
  items:
    type: blacklist # Whitelist if you want only those items to be allowed and blacklist (recommended) for the items to be blocked
    list: # Whitelist or Blacklist based on the options above
      -

    enchants:
      type: blacklist # Whitelist if you want only selected enchants to be allowed and blacklist (recommended) for the enchants to be blocked
      list: # Whitelist or Blacklist based on the options above
        -

      max-enchants: -1 # Max enchants an item can have. -1 to disable

filler: # Fill your GUI's empty slots into filler items
  filler-item: true
  item:
    material: GRAY_STAINED_GLASS_PANE
    name: " "
    lore: [ ]
    glow: false

# Configuration Done! Such a small config