name: ChamoOrders
version: '${version}'

main: net.chamosmp.ChamoOrders.ChamoOrdersPlugin
loader: net.chamosmp.ChamoOrders.ChamoOrdersLoader
api-version: '1.21.11'

folia-supported: true

dependencies:
  server:
    Vault:
      load: BEFORE
      required: false
      join-classpath: true
    PlaceholderAPI:
      load: BEFORE
      required: false
      join-classpath: true

permissions:
  chamoparty.order:
    default: not op
    description: "This permission allows using /order"
    children:
      permission.node.child: true
  chamoorders.admin:
    default: op
    description: "Allows using the admin commands"
    children:
      permission.node.child: true
  chamoorders.admin.reload:
    default: op
    description: "Allows using /reload"
    children:
      permission.node.child: true